title: intro-to-atfg
description: Intro to ATFG
steps:
  - link: 'https://atfg.gtechindia.org'
    title: Introduction
    description: >-
      There are many more courses available on Learning Lab for you to check
      out.

  - course: githubtraining/introduction-to-github
    description: The first step in your course