title: Intro to ATFG for Enablers
description: Intro to ATFG for Enablers
steps:
  - link: 'https://atfg.gtechindia.org/program/#what-is-industry-ready'
    title: What is Industry Ready?
    description: >-
      On this page, we first explore the notion of "Industry Ready".
  - link: 'https://atfg.gtechindia.org/program/#atfg-elements'
    title: Core Elements of the program
    description: >-
      In this section, we learn about the different elements of the program.
  - link: 'https://atfg.gtechindia.org/program/#atfg-activities'
    title: What are the activities for Students, Mentors and Enablers?
    description: >-
      ATFG has prepared a range of activities for Students, Mentors and Enablers.
  - link: 'https://atfg.gtechindia.org/program/#atfg-benefits'
    title: Why ATFG?
    description: >-
      Let's explore some of the benefits of ATFG for Students, and for Kerala.