title: Intro to ATFG for Enablers
description: Intro to ATFG for Enablers
steps:
  - link: 'https://atfg.gtechindia.org/program/#what-is-industry-ready'
    title: What is Industry Ready?
    description: >-
      On this page, we first explore the notion of "Industry Ready".
  - link: 'https://atfg.gtechindia.org/program/#atfg-elements'
    title: Core Elements of the progrma
    description: >-
        On this page, we first explore the notion of "Industry Ready".
  - link: 'https://atfg.gtechindia.org/program/#atfg-activities'
    title: What are the activities for Students, Mentors and Enablers?
    description: >-
      On this page, we first explore the notion of "Industry Ready". Then, to the core elements of our system. Our <a href="https://atfg.gtechindia.org/program/#atfg-activities">current activities</a> are listed.
  - link: 'https://atfg.gtechindia.org/program/#atfg-benefits'
    title: Introduction
    description: >-
      On this page, we first explore the notion of "Industry Ready". Then, to the core elements of our system. Our <a href="https://atfg.gtechindia.org/program/#atfg-activities">current activities</a> are listed.
